services:
  angular:
    build: .
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
